esphome:
  name: clim
  friendly_name: Clim

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FyjdOh6X7yUrxCGROtzlWp8VVFmtOkvZ1yLK+iH8JXQ="

ota:
  - platform: esphome
    password: "c6f21a496e99faf98524965256c65c32"

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Clim Fallback Hotspot"
    password: "aMgwxKA0wCzY"

captive_portal:

# Add the dependency to pull in the fujitsu heat pump component
external_components:
  - source: github://manny42/esphome-fujitsu


climate:
  - platform: fujitsu_heat_pump
    name: My Fujitsu Heat Pump
    # The rest of these options are optional
    tx_pin: 17
    rx_pin: 16
    remote_temperature_id: some_temp_sensor # TODO see FujitsuClimate.cpp to correct the implementation
    master: false

# Pull a sensor in from homeassistant
sensor:
  - platform: homeassistant
    entity_id: sensor.zigbee_sensor
    id: some_temp_sensor